// <auto-generated />
namespace Car_Spare_Parts_company.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updat_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updat_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202207051634276_updat_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
