using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Car_Spare_Parts_company
{
    public partial class XtraForm1 : DevExpress.XtraEditors.XtraForm
    {
        Car_Company_DB md2;
        public XtraForm1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Car_Spare_Parts_company.Car_Company_DB dbContext = new Car_Spare_Parts_company.Car_Company_DB();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Refunds.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.Refunds.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void XtraForm1_Load(object sender, EventArgs e)
        {

            md2 = new Car_Company_DB();


            gridControl1.DataSource = md2.Refunds.ToList();
            md2 = new Car_Company_DB();
            
            comboBoxEdit1.Properties.Items.Clear();
            
            comboBoxEdit1.Properties.Items.AddRange(md2.Clients.Select(r => r.Name).ToArray());
        }

        private void comboBoxEdit1_SelectedIndexChanged(object sender, EventArgs e)
        {
            var result = md2.Refunds.Where(er => er.ClientName == comboBoxEdit1.SelectedItem.ToString());
            gridControl1.DataSource = result.ToList();
        }
                            
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            
            if (textEdit1.Text.Length != 0)
            {

                var result = md2.Refunds.Where(er => er.Productname == textEdit1.Text);
                gridControl1.DataSource = result.ToList();
            }
            else
            {
                gridControl1.DataSource = md2.Refunds.ToList();
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Hide();
            XtraForm2 ct = new XtraForm2(this);

            ct.ShowDialog();
            Close();
        }

       

        private void gridDelete_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

            if (XtraMessageBox.Show($"are you sure you want to delete {(gridView1.GetFocusedRow() as Refunds).ClientName}", "message", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                var id = (gridView1.GetFocusedRow() as Refunds).id;
                var prodName = (gridView1.GetFocusedRow() as Refunds).Productname;
                var we =  md2.Refunds.SingleOrDefault(h=>h.id==id);
                md2.Refunds.Remove(we);
             
                md2.products.Where(r => r.Name == prodName).SingleOrDefault().Amount -= (gridView1.GetFocusedRow() as Refunds).amount;
                md2.SaveChanges();

                XtraForm1_Load(null, null);
            }

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            gridControl1.DataSource = null;
        }

        private void XtraForm1_FormClosed(object sender, FormClosedEventArgs e)
        {
            Hide();
            Dashboard df = new Dashboard(new UserControl1());
            df.ShowDialog();
            Close();
        }
    }
}